#!/bin/sh
# See LICENSE file for copyright and license details.

usage() {
	echo 'usage: wsclean [-d] file1 file2 ...' >&2 
	exit 1
}

while getopts :d opt; do
	case "$opt" in
	d)	safe=1 ;;
	?)	usage ;;
	esac
done

shift $((OPTIND - 1))

files=$(echo "$@" | sed -E 's/-.[[:space:]]?//g')
! [ "$files" ] && usage

for file in $files; do
	sed -E 's/[[:space:]]*$//' "$file" > "$file.new"
	! [ "$safe" ] && mv "$file.new" "$file"
done
