#!/bin/sh
# See LICENSE file for copyright and license details.

set -e

usage() {
	echo 'usage: wsclean [-d] file' >&2
	exit 1
}

while getopts :d opt; do
	case "$opt" in
	d)	safe=1 ;;
	?)	usage ;;
	esac
done

shift $((OPTIND - 1))

! [ "$1" ] && usage

sed -E 's/[[:space:]]*$//' "$1" > "$1.new"
! [ "$safe" ] && mv "$1.new" "$1"

exit 0
